#!/usr/bin/env bash
# Streamlined onboarding: add a new Discord bot instance by pasting tokens and config.
# Run on the VPS (where the broker runs). Creates /opt/openclaw-bot-<instance>/ and bot.env.
#
# Usage:
#   ./deploy/onboard_bot.sh [instance_name] [--enable]
#   # Interactive: prompts for instance name (if omitted), DISCORD_TOKEN, BOT_TOKEN, BROKER_URL, allowlist ID(s).
#   # --enable: enable and start the systemd unit at the end (no prompt).
#
# Non-interactive (all set in env):
#   INSTANCE_NAME=urgoclaw DISCORD_TOKEN=... BOT_TOKEN=... BROKER_URL=... ALLOWED_USER_ID=... ./deploy/onboard_bot.sh
#   # Add --enable or ONBOARD_START=1 to enable and start without prompting.
#
# Prerequisites: broker.env has BOT_TOKEN; you have a Discord Application and bot token; your Discord user ID.

set -e
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
ARG1="${1:-}"
ARG2="${2:-}"
# Optional --enable flag (or second arg)
if [[ "$ARG1" == "--enable" ]]; then
  ONBOARD_START=1
  INSTANCE_NAME="${INSTANCE_NAME:-}"
elif [[ "$ARG2" == "--enable" ]]; then
  ONBOARD_START=1
  INSTANCE_NAME="${ARG1:-$INSTANCE_NAME}"
else
  INSTANCE_NAME="${ARG1:-$INSTANCE_NAME}"
fi

if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
  SUDO=()
elif command -v sudo >/dev/null 2>&1; then
  SUDO=(sudo)
else
  echo "Error: this script needs root privileges for /opt and systemd. Re-run as root or install sudo." >&2
  exit 1
fi

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: required command '$cmd' is not installed or not in PATH." >&2
    exit 1
  fi
}

run_root() {
  "${SUDO[@]}" "$@"
}

# Write a single env line; value is quoted and escaped so secrets are safe in the file.
_write_env_line() {
  local key="$1"
  local val="$2"
  if [[ -z "$val" ]]; then
    return
  fi
  # Escape backslash then double-quote for use inside double quotes
  local escaped
  escaped=$(printf '%s' "$val" | sed 's/\\/\\\\/g; s/"/\\"/g')
  printf '%s="%s"\n' "$key" "$escaped"
}

require_cmd python3
require_cmd systemctl

# --- Gather config ---
if [[ -z "$INSTANCE_NAME" ]]; then
  echo "Instance name (e.g. urgoclaw, clawhub):"
  read -r INSTANCE_NAME
  INSTANCE_NAME=$(echo "$INSTANCE_NAME" | tr -d '[:space:]')
  if [[ -z "$INSTANCE_NAME" ]]; then
    echo "Error: instance name is required." >&2
    exit 1
  fi
fi

OPT_DIR="/opt/openclaw-bot-${INSTANCE_NAME}"
BOT_ENV="${OPT_DIR}/bot.env"

# Non-interactive: require all vars set
if [[ -n "$DISCORD_TOKEN" && -n "$BOT_TOKEN" && -n "$BROKER_URL" && ( -n "$ALLOWED_USER_ID" || -n "$ALLOWLIST_USER_ID" ) ]]; then
  echo "[onboard_bot] Non-interactive: using env for instance=$INSTANCE_NAME"
else
  echo "[onboard_bot] Interactive onboarding for instance: $INSTANCE_NAME"
  echo ""

  echo "Paste DISCORD_TOKEN (Bot token from Discord Developer Portal â†’ Your App â†’ Bot):"
  read -rs DISCORD_TOKEN
  echo ""
  echo "Paste BOT_TOKEN (must match broker's BOT_TOKEN / X-Bot-Token):"
  read -rs BOT_TOKEN
  echo ""
  echo "BROKER_URL (e.g. http://127.0.0.1:8000 or http://100.x.x.x:8443):"
  read -r BROKER_URL
  BROKER_URL=$(echo "$BROKER_URL" | sed 's|/$||')
  echo "ALLOWED_USER_ID (your Discord user ID; Developer Mode â†’ right-click you â†’ Copy ID):"
  read -r ALLOWED_USER_ID
  echo "ALLOWLIST_USER_ID (optional; comma/space separated extra user IDs, or leave empty):"
  read -r ALLOWLIST_USER_ID
  echo "ALLOWED_CHANNEL_ID (optional; single channel ID for non-DM, or leave empty for DMs only):"
  read -r ALLOWED_CHANNEL_ID
fi

# Validate
if [[ -z "$DISCORD_TOKEN" || -z "$BOT_TOKEN" || -z "$BROKER_URL" ]]; then
  echo "Error: DISCORD_TOKEN, BOT_TOKEN, and BROKER_URL are required." >&2
  exit 1
fi
if [[ -z "$ALLOWED_USER_ID" && -z "$ALLOWLIST_USER_ID" ]]; then
  echo "Error: set at least one of ALLOWED_USER_ID or ALLOWLIST_USER_ID." >&2
  exit 1
fi
if [[ ! "$BROKER_URL" =~ ^https?:// ]]; then
  echo "Error: BROKER_URL must start with http:// or https://. Got: $BROKER_URL" >&2
  exit 1
fi

# 1) Run install script (creates dirs, venv, systemd template; does NOT create bot.env or start)
echo "[onboard_bot] Running install_bot_instance.sh ..."
bash "$REPO_ROOT/deploy/install_bot_instance.sh" "$INSTANCE_NAME"
# install script copies bot.env.example to $OPT_DIR/bot.env.example; we write bot.env next

# 2) Write bot.env (no secrets in logs)
echo "[onboard_bot] Writing $BOT_ENV ..."
{
  echo "# Generated by onboard_bot.sh â€” do not commit."
  _write_env_line "DISCORD_TOKEN" "$DISCORD_TOKEN"
  _write_env_line "BOT_TOKEN" "$BOT_TOKEN"
  _write_env_line "BROKER_URL" "$BROKER_URL"
  _write_env_line "ALLOWED_USER_ID" "$ALLOWED_USER_ID"
  _write_env_line "ALLOWLIST_USER_ID" "$ALLOWLIST_USER_ID"
  _write_env_line "ALLOWED_CHANNEL_ID" "$ALLOWED_CHANNEL_ID"
  echo "# Optional (defaults in code): JOB_POLL_INTERVAL_SEC, JOB_POLL_TIMEOUT_SEC, BOT_COOLDOWN_SECONDS, BOT_MAX_CONCURRENT"
} | run_root tee "$BOT_ENV" >/dev/null

run_root chown openclaw:openclaw "$BOT_ENV"
echo "[onboard_bot] bot.env created and owned by openclaw."

# 3) Enable and start (prompt unless ONBOARD_START=1 or --enable)
echo ""
if [[ -n "$ONBOARD_START" ]]; then
  run_root systemctl enable --now "openclaw-discord-bot@${INSTANCE_NAME}"
  echo "[onboard_bot] Enabled and started. Logs: journalctl -u openclaw-discord-bot@$INSTANCE_NAME -f"
  if ! run_root systemctl is-active --quiet "openclaw-discord-bot@${INSTANCE_NAME}"; then
    echo "[onboard_bot] Bot did not reach active state. Next checks:" >&2
    echo "  ${SUDO[*]:+${SUDO[*]} }systemctl status openclaw-discord-bot@$INSTANCE_NAME --no-pager" >&2
    echo "  ${SUDO[*]:+${SUDO[*]} }journalctl -u openclaw-discord-bot@$INSTANCE_NAME -n 50 --no-pager" >&2
    exit 1
  fi
else
  echo "Start the bot: ${SUDO[*]:+${SUDO[*]} }systemctl enable --now openclaw-discord-bot@$INSTANCE_NAME"
  printf "Enable and start now? [y/N] "
  read -r ans
  if [[ "$ans" =~ ^[yY] ]]; then
    run_root systemctl enable --now "openclaw-discord-bot@${INSTANCE_NAME}"
    echo "[onboard_bot] Started. Logs: ${SUDO[*]:+${SUDO[*]} }journalctl -u openclaw-discord-bot@$INSTANCE_NAME -f"
  fi
fi

echo ""
echo "Done. DM the bot 'whoami' to confirm instance and broker URL."
