#!/usr/bin/env bash
# Create runner.env by pasting BROKER_URL and WORKER_TOKEN (from broker onboarding).
# Run from repo root (e.g. on WSL). No sudo. Use the tokens printed by onboard_broker.sh.

set -e
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
RUNNER_ENV="${REPO_ROOT}/runner/runner.env"

_write_env_line() {
  local key="$1"
  local val="$2"
  if [[ -z "$val" ]]; then
    return
  fi
  local escaped
  escaped=$(printf '%s' "$val" | sed 's/\\/\\\\/g; s/"/\\"/g')
  printf '%s="%s"\n' "$key" "$escaped"
}

if [[ -n "$BROKER_URL" && -n "$WORKER_TOKEN" ]]; then
  echo "[onboard_runner] Using env: BROKER_URL=$BROKER_URL"
  WORKER_ID="${WORKER_ID:-}"
else
  echo "[onboard_runner] Paste values from broker onboarding (onboard_broker.sh output)."
  echo "BROKER_URL (e.g. http://100.x.x.x:8443 or http://127.0.0.1:8000):"
  read -r BROKER_URL
  BROKER_URL=$(echo "$BROKER_URL" | sed 's|/$||')
  echo "WORKER_TOKEN:"
  read -r WORKER_TOKEN
  echo "WORKER_ID (optional; default hostname):"
  read -r WORKER_ID
fi

if [[ -z "$BROKER_URL" || -z "$WORKER_TOKEN" ]]; then
  echo "Error: BROKER_URL and WORKER_TOKEN are required." >&2
  exit 1
fi

{
  echo "# Generated by onboard_runner.sh — do not commit."
  _write_env_line "BROKER_URL" "$BROKER_URL"
  _write_env_line "WORKER_TOKEN" "$WORKER_TOKEN"
  _write_env_line "WORKER_ID" "$WORKER_ID"
  echo "# Optional: POLL_INTERVAL_SEC=10, RESULT_TIMEOUT_SEC=300, RUNNER_REPOS_BASE, RUNNER_REPO_ALLOWLIST, etc."
} > "$RUNNER_ENV"
echo "[onboard_runner] Wrote $RUNNER_ENV"
echo ""
echo "Run the runner: cd $REPO_ROOT && export \$(grep -v '^#' runner/runner.env | xargs) && python runner/runner.py"
echo "Or: runner/start.sh (if it sources runner.env)."
