#!/usr/bin/env bash
# One-shot broker install + config: venv, systemd unit, broker.env, data dir, optional start.
# Run on the VPS from repo root. No secrets in repo; tokens generated or pasted.
#
# Usage:
#   ./deploy/onboard_broker.sh
#   # Interactive: prompts for BROKER_HOST (bind address), BROKER_PORT, generate or paste tokens.
#
#   ./deploy/onboard_broker.sh --enable
#   # Same, then enable and start the systemd unit without prompting.
#
# Non-interactive (set env; tokens generated if not set):
#   BROKER_HOST=100.x.x.x BROKER_PORT=8443 ./deploy/onboard_broker.sh --enable
#   WORKER_TOKEN=... BOT_TOKEN=... BROKER_HOST=127.0.0.1 ./deploy/onboard_broker.sh --enable

set -e
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
BROKER_ENV_DIR="/opt/openclaw-broker"
BROKER_ENV_FILE="${BROKER_ENV_DIR}/broker.env"
STATE_DIR="/var/lib/openclaw-broker"
SERVICE_NAME="openclaw-broker"
ONBOARD_START="${ONBOARD_START:-}"
[[ "${1:-}" == "--enable" ]] && ONBOARD_START=1

_write_env_line() {
  local key="$1"
  local val="$2"
  if [[ -z "$val" ]]; then
    return
  fi
  local escaped
  escaped=$(printf '%s' "$val" | sed 's/\\/\\\\/g; s/"/\\"/g')
  printf '%s="%s"\n' "$key" "$escaped"
}

# 1) Ensure broker is installed (venv + systemd unit)
if [[ ! -f /etc/systemd/system/${SERVICE_NAME}.service ]]; then
  echo "[onboard_broker] Installing broker (venv + systemd unit) ..."
  "$REPO_ROOT/deploy/scripts/install_broker.sh"
else
  echo "[onboard_broker] Broker unit already installed."
fi

# 2) Gather config
if [[ -n "$BROKER_HOST" && -n "$BROKER_PORT" ]]; then
  echo "[onboard_broker] Using env: BROKER_HOST=$BROKER_HOST BROKER_PORT=$BROKER_PORT"
  # Tokens: use existing or generate
  if [[ -z "$WORKER_TOKEN" ]]; then
    WORKER_TOKEN=$(openssl rand -hex 32)
    echo "[onboard_broker] Generated new WORKER_TOKEN"
  fi
  if [[ -z "$BOT_TOKEN" ]]; then
    BOT_TOKEN=$(openssl rand -hex 32)
    echo "[onboard_broker] Generated new BOT_TOKEN"
  fi
else
  echo "[onboard_broker] Interactive broker configuration"
  echo ""
  echo "BROKER_HOST (bind address; use Tailscale IP for tailnet-only, e.g. 100.x.x.x):"
  printf "  [127.0.0.1] "
  read -r BROKER_HOST
  BROKER_HOST="${BROKER_HOST:-127.0.0.1}"
  echo "BROKER_PORT:"
  printf "  [8000] "
  read -r BROKER_PORT
  BROKER_PORT="${BROKER_PORT:-8000}"

  echo ""
  printf "Generate new WORKER_TOKEN and BOT_TOKEN? [Y/n] "
  read -r gen
  if [[ "$gen" =~ ^[nN] ]]; then
    echo "Paste WORKER_TOKEN:"
    read -r WORKER_TOKEN
    echo "Paste BOT_TOKEN:"
    read -r BOT_TOKEN
  else
    WORKER_TOKEN=$(openssl rand -hex 32)
    BOT_TOKEN=$(openssl rand -hex 32)
    echo "[onboard_broker] Generated new tokens."
  fi
fi

# 3) Write broker.env
sudo mkdir -p "$BROKER_ENV_DIR"
{
  echo "# Generated by onboard_broker.sh — do not commit."
  _write_env_line "BROKER_DB" "${STATE_DIR}/broker.db"
  _write_env_line "WORKER_TOKEN" "$WORKER_TOKEN"
  _write_env_line "BOT_TOKEN" "$BOT_TOKEN"
  _write_env_line "BROKER_HOST" "$BROKER_HOST"
  _write_env_line "BROKER_PORT" "$BROKER_PORT"
} | sudo tee "$BROKER_ENV_FILE" >/dev/null
echo "[onboard_broker] Wrote $BROKER_ENV_FILE"

# 4) Data dir
sudo mkdir -p "$STATE_DIR"
sudo chown openclaw:openclaw "$STATE_DIR"
[[ -f "${STATE_DIR}/broker.db" ]] && sudo chown openclaw:openclaw "${STATE_DIR}/broker.db"
echo "[onboard_broker] Data dir $STATE_DIR ready"

# 5) Show tokens once (so user can copy for runner and bots)
echo ""
echo "--- Save these for the runner and Discord bot(s) ---"
echo "WORKER_TOKEN=$WORKER_TOKEN"
echo "BOT_TOKEN=$BOT_TOKEN"
echo "BROKER_URL=http://${BROKER_HOST}:${BROKER_PORT}"
echo "---"
echo ""

# 6) Enable and start
if [[ -n "$ONBOARD_START" ]]; then
  sudo systemctl enable "$SERVICE_NAME"
  sudo systemctl start "$SERVICE_NAME"
  echo "[onboard_broker] Enabled and started $SERVICE_NAME"
  sleep 1
  sudo systemctl status "$SERVICE_NAME" --no-pager || true
  curl -s "http://${BROKER_HOST}:${BROKER_PORT}/health" && echo "" || echo "Health check failed or wrong host/port."
else
  echo "Enable and start: sudo systemctl enable --now $SERVICE_NAME"
  printf "Enable and start now? [y/N] "
  read -r ans
  if [[ "$ans" =~ ^[yY] ]]; then
    sudo systemctl enable --now "$SERVICE_NAME"
    echo "[onboard_broker] Started. Logs: journalctl -u $SERVICE_NAME -f"
  fi
fi

echo ""
echo "Done. Use deploy/onboard_bot.sh to add Discord bot instances; use WORKER_TOKEN and BROKER_URL for the runner."
