#!/bin/bash
# Setup script for VPS runner with SSH key authentication
# This script configures the VPS to accept remote CLI commands from the WSL runner
#
# Usage: ./setup_vps_runner.sh [--host VPS_HOST] [--user VPS_USER]

set -e

# Default values
VPS_HOST="${VPS_HOST:-}"
VPS_USER="${VPS_USER:-openclaw}"
SSH_KEY_PATH="${VPS_SSH_KEY_PATH:-$HOME/.ssh/openclaw_vps_runner}"
SSH_DIR="$HOME/.ssh"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --host)
            VPS_HOST="$2"
            shift 2
            ;;
        --user)
            VPS_USER="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [--host VPS_HOST] [--user VPS_USER]"
            echo ""
            echo "Environment variables:"
            echo "  VPS_HOST         - VPS hostname or IP address"
            echo "  VPS_USER         - Username on VPS (default: openclaw)"
            echo "  VPS_SSH_KEY_PATH - Path to save SSH key (default: ~/.ssh/openclaw_vps_runner)"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Validate VPS_HOST
if [[ -z "$VPS_HOST" ]]; then
    log_error "VPS_HOST is required. Set via environment variable or --host flag."
    exit 1
fi

echo "============================================"
echo "VPS Runner Setup - SSH Key Configuration"
echo "============================================"
echo "VPS Host: $VPS_HOST"
echo "VPS User: $VPS_USER"
echo "SSH Key:  $SSH_KEY_PATH"
echo "============================================"
echo ""

# Create SSH directory if needed
if [[ ! -d "$SSH_DIR" ]]; then
    log_info "Creating SSH directory: $SSH_DIR"
    mkdir -p "$SSH_DIR"
    chmod 700 "$SSH_DIR"
fi

# Generate SSH key if it doesn't exist
if [[ ! -f "$SSH_KEY_PATH" ]]; then
    log_info "Generating new SSH key pair..."
    ssh-keygen -t ed25519 -a 100 -f "$SSH_KEY_PATH" -N "" -C "openclaw_vps_runner_$(date +%Y%m%d)"
    log_success "SSH key generated: $SSH_KEY_PATH"
else
    log_warn "SSH key already exists: $SSH_KEY_PATH"
fi

# Display public key
echo ""
log_info "Your public key (copy this to VPS authorized_keys):"
echo "============================================"
cat "${SSH_KEY_PATH}.pub"
echo "============================================"
echo ""

# Check if we can connect to VPS
log_info "Testing SSH connection to VPS..."
if ssh -o "StrictHostKeyChecking=accept-new" -o "ConnectTimeout=5" -i "$SSH_KEY_PATH" "${VPS_USER}@${VPS_HOST}" "echo 'SSH connection successful'" 2>/dev/null; then
    log_success "SSH connection successful!"
else
    log_warn "Could not connect to VPS via SSH."
    echo ""
    echo "To complete setup, run the following on your VPS as root:"
    echo ""
    echo "1. Create the user (if not exists):"
    echo "   useradd -m -s /bin/bash $VPS_USER"
    echo ""
    echo "2. Create .ssh directory:"
    echo "   mkdir -p /home/$VPS_USER/.ssh"
    echo "   chmod 700 /home/$VPS_USER/.ssh"
    echo "   chown $VPS_USER:$VPS_USER /home/$VPS_USER/.ssh"
    echo ""
    echo "3. Add the public key to authorized_keys:"
    echo "   echo '$(cat ${SSH_KEY_PATH}.pub)' >> /home/$VPS_USER/.ssh/authorized_keys"
    echo "   chmod 600 /home/$VPS_USER/.ssh/authorized_keys"
    echo "   chown $VPS_USER:$VPS_USER /home/$VPS_USER/.ssh/authorized_keys"
    echo ""
    echo "4. Configure sudo access (for nginx/certbot):"
    echo "   echo '$VPS_USER ALL=(ALL) NOPASSWD: /usr/sbin/nginx, /usr/bin/systemctl reload nginx, /usr/bin/systemctl status nginx, /usr/bin/certbot' > /etc/sudoers.d/openclaw"
    echo "   chmod 440 /etc/sudoers.d/openclaw"
    echo ""
fi

# Create runner environment file
echo ""
log_info "Creating runner environment configuration..."
ENV_FILE="runner_vps.env"
cat > "$ENV_FILE" << EOF
# VPS Remote Execution Configuration
# Generated by setup_vps_runner.sh on $(date)

# VPS SSH Connection
VPS_HOST=$VPS_HOST
VPS_USER=$VPS_USER
VPS_SSH_KEY_PATH=$SSH_KEY_PATH
VPS_SSH_PORT=22

# Command timeout (seconds)
VPS_CMD_TIMEOUT=60

# Maximum output size (bytes)
VPS_MAX_OUTPUT_BYTES=50000

# Website base path on VPS
VPS_WEBSITE_BASE=/var/www/urgo
EOF

log_success "Environment file created: $ENV_FILE"
echo ""

# Test configuration
echo ""
log_info "Testing VPS connection with configuration..."
if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
    
    # Try to run a simple command
    if ssh -o "StrictHostKeyChecking=accept-new" -o "ConnectTimeout=5" -i "$VPS_SSH_KEY_PATH" "${VPS_USER}@${VPS_HOST}" "uptime" 2>/dev/null; then
        log_success "VPS connection test successful!"
    else
        log_warn "Could not connect to VPS. Please complete the manual setup steps above."
    fi
fi

echo ""
echo "============================================"
echo "Setup Summary"
echo "============================================"
echo "SSH Key:       $SSH_KEY_PATH"
echo "Public Key:    ${SSH_KEY_PATH}.pub"
echo "Config File:   $ENV_FILE"
echo ""
echo "To use this configuration:"
echo "  1. Source the environment file:"
echo "     source $ENV_FILE"
echo ""
echo "  2. Or add to your runner.env:"
echo "     cat $ENV_FILE >> runner/runner.env"
echo ""
echo "  3. Test the connection:"
echo "     python -c 'from runner.vps_remote_executor import test_vps_connection; print(test_vps_connection())'"
echo ""
echo "============================================"
log_success "Setup complete!"
